### ISSUE TITLE
Visual Studio 2022 solution only builds the RelWithDebInfo configuration

### ISSUE THREAD

**Issue by SteveMaas1978** [NGSolve/ngsolve#66]
Hi, I am trying to build the source code from scratch (I only want netgen, but it was recommended somewhere to build ngsolve instead). I use the cmake file to generate the solution for Visual Studio 2022. The default configuration selected is Debug and the build succeeds without errors, but the files are placed in a folder called RelWithDebInfo. Then, when I choose the Release configuration, it still puts the final files in that same folder. So, it seems to me that the build is not respecting the selected configuration. Is there a solution to this? Thanks!

**Comment by mhochsteger** [comment]
The CMake project also installs dependencies (like netgen) automatically. Due to this Superbuild structure the build configuration cannot be respected at all levels.
To get a consistent configuration, you can pass '-DCMAKE_BUILD_TYPE=Debug' when configuring ngsolve. This setting is passed to the dependencies (like netgen) aswell.

Alternatively, you can configure with '-DUSE_SUPERBUILD=OFF', this will result in just one solution and behave as you expect it, but you have to take care of all dependencies yourself.
